server:
  port: 8080

app:
  name: pantau
  env: development

database:
  max_open_conns: 25
  max_idle_conns: 10

migration:
  enabled: true

gorm:
  show_sql: true

upload:
  enabled: true
  max_file_size: 5MB
  max_request_size: 20MB

logging:
  level: INFO

jwt:
  expiration: 168h
